dist: xenial

services:
  - docker

branches:
  only:
    - master

notifications:
  slack: ibm-cloudplatform:A0dghgxajjlRicfCGqLumVKE

language: python
python:
  - "3.8"
  - "3.9"

install:
  - pip3 install flake8
  - pip install pytest-cov
  - pip install -r requirements.txt

script:
  - flake8 src/app  --ignore F401,F403
  - flake8 src/tests --ignore E501
  - echo ok
  - bash run_tests.sh

before_deploy:
   - bash sonar_scanner.sh

deploy:
    provider: script
    script: bash deploy.sh
    on:
      branch: master
      condition: $TRAVIS_PYTHON_VERSION == 3.8